url: http://61924.nl
cdn: https://dl.dropbox.com/u/18064043/61924.nl
debug: false

safe: false

exclude: [rakefile.rb]

markdown: rdiscount
pygments: true
permalink: /:month-:day-:year/:title.html

rdiscount:
  extensions: [smart, strict]
