url: http://localhost:4000
cdn: http://cdn.61924.nl
debug: true

safe: false

exclude: [rakefile.rb]

markdown: rdiscount
pygments: true
permalink: /:month-:day-:year/:title.html

rdiscount:
  extensions: [smart, strict]
