url: http://61924.nl
cdn: http://cdn.61924.nl
debug: false

safe: false

exclude: [rakefile.rb]

markdown: rdiscount
pygments: true
permalink: /:month-:day-:year/:title.html

rdiscount:
  extensions: [smart, strict]
