url: http://61924.nl
cdn: http://cdn.61924.nl
debug: false

safe: false

exclude: [rakefile.rb]

markdown: kramdown
pygments: true
permalink: /:month-:day-:year/:title.html

rdiscount:
  extensions: [smart, strict]

kramdown:
  auto_ids: false,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
