url: http://localhost:4000
cdn: http://61924.nl/static
debug: true

safe: false

exclude: [rakefile.rb]

markdown: rdiscount
pygments: true
permalink: /:month-:day-:year/:title.html

rdiscount:
  extensions: [smart, strict]
